# Generated by Django 3.2 on 2021-05-01 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_carpark_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='slot_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
