# Generated by Django 3.2 on 2021-05-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_carpark_slot_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carpark')),
            ],
        ),
    ]
