# Generated by Django 3.2 on 2021-05-01 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_unpark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpark',
            name='slot_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
