# Generated by Django 3.2 on 2021-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_unpark_slot_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='car_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
