# Generated by Django 3.2 on 2021-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='ip_adress',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
