# Generated by Django 3.2 on 2021-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rate_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='time_field',
            field=models.FloatField(null=True),
        ),
    ]
